#!/bin/bash
# index.edit -- compile list of index entries for editing.

# delimiter of the first `s` command
A="$(tr 'x' '\001' <<<'x')"
# delimiter of the second `s` command (the one generated by the replacement field of the first `s`)
B="$(tr 'x' '\002' <<<'x')"
# Why is `sort -u` important?{{{
#
# To remove duplicate lines.
# If we keep duplicate lines, we may perform two substitutions on the same line,
# which may have unexpected results.
#}}}
grep '^\.XX' "$@" \
  | sort -u \
  | sed "s${A}^\.XX \(.*\)\$${A}/^\\.XX /s${B}\1${B}\1${B}${A}"
  #                               ├┘{{{
  #                               └ the first backslash protects the dot from the first `s` command;
  #
  #                                 the second backslash protects the dot from sed
  #                                 when it will run the the second `s` command
  #}}}

# Note that the first `s` command is going to be run now by the script, but not the second one.{{{
#
# The second one is just written in the replacement field of the first `s` command.
# It will be run later, after we redirected the output of this script in a file,
# edited and review the latter, then run it as a sed script.
#}}}
